name: rxflare
description: A high-performance reactive state management library for Flutter featuring automatic dependency tracking and granular field-level updates.
version: 1.6.5
homepage: https://github.com/msfm2018/rxflare
repository: https://github.com/msfm2018/rxflare
issue_tracker: https://github.com/msfm2018/rxflare/issues

topics:
  - state-management
  - reactive
  - flutter-widgets
  - performance

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:



example: example/lib/main.dart