name: rxflare
description: >
  A high-performance reactive state management library for Flutter. 
  Supports automatic dependency tracking, granular field-level updates 
  for Maps/Lists, and a lightweight Rx widget to minimize boilerplate.
version: 1.1.8
homepage: https://github.com/msfm2018/rxflare
repository: https://github.com/msfm2018/rxflare

topics:
  - state-management
  - reactive
  - flutter-widgets
  - performance

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
linter:
  rules:
    public_member_api_docs: true
    require_trailing_commas: true   # 可选，提高代码风格

example: example/lib/main.dart